spring.application.name=hermecard-auth-api

jwt.secret=jW5vunRAcuQc569wdaft0tTsdhSQcvZ89KNbJ5bnFVc=

spring.datasource.url=jdbc:postgresql://localhost:5432/hermecarddb
spring.datasource.username=postgres
spring.datasource.password=NeverEndingWar64

spring.sql.init.mode=always
