spring.application.name=hermecard-api
server.port=8081

# R2DBC — conexão reativa com PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/hermecarddb
spring.r2dbc.username=postgres
spring.r2dbc.password=NeverEndingWar64

# Inicialização do schema via SQL (cria tabela cards se não existir)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# ✅ Aponta para o Authorization Server para validar tokens via OIDC discovery
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080

# Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.r2dbc=DEBUG