spring.application.name=hermecard-auth-api

spring.datasource.url=jdbc:postgresql://localhost:5432/hermecarddb
spring.datasource.username=postgres
spring.datasource.password=NeverEndingWar64

spring.sql.init.mode=always
